### ISSUE TITLE
Group Analysis

### ISSUE THREAD

**Issue by smeisler** [mandymejia/BayesGLMfMRI#21]
I am using `BayesGLM2` / `BayesGLM_group` to run a second-level analysis. For each subject I have an overall results .rds object that was the result of saving the output from `BayesGLM_cifti`. I also have the two individual hemisphere files that were created by the `BayesGLM_cifti command`.

After collecting each subject's outputs with `out_files<-Sys.glob(file.path(outdir,'*/BayesGLM.rds'))`, I run the following command:

```
BayesGLM2(
  results = out_files,
  contrasts = NULL,
  quantiles = NULL,
  excursion_type = NULL,
  gamma = 0,
  alpha = 0.05,
  nsamp_theta = 50,
  nsamp_beta = 100,
  no_cores = parallel::detectCores() - 2,
  verbose = TRUE
)
```
When using the combined BayesGLM outputs, I get the following error:
```
Error in BayesGLM2(results = out_files, contrasts = NULL, quantiles = NULL, : Each RDS file in results argument must contain an object of class BayesGLM
Traceback:

1. BayesGLM2(results = out_files, contrasts = NULL, quantiles = NULL, 
 .     excursion_type = NULL, gamma = 0, alpha = 0.05, nsamp_theta = 50, 
 .     nsamp_beta = 100, no_cores = parallel::detectCores() - 2, 
 .     verbose = TRUE)
2. stop("Each RDS file in results argument must contain an object of class BayesGLM")
```
When using a hemisphere specific output, I get the following error:
```
Setting up contrast vectors to compute the average across subjects for each task. If other contrasts are desired, provide a contrasts argument.
Error in X_list %*% Amat.final: Cholmod error 'A and B inner dimensions must match' at file ../MatrixOps/cholmod_ssmult.c, line 80
Traceback:

1. BayesGLM2(results = out_files, contrasts = NULL, quantiles = NULL, 
 .     excursion_type = NULL, gamma = 0, alpha = 0.05, nsamp_theta = 50, 
 .     nsamp_beta = 100, no_cores = parallel::detectCores() - 2, 
 .     verbose = TRUE)
2. X_list %*% Amat.final
3. X_list %*% Amat.final
```
These results were calculated today after updating all relevant R packages (e.g. BayesfMRI, ciftiTools). Please let me know how I should proceed or if any other information would be useful.

Thanks,
Steven

**Comment by damondpham** [comment]
Hi Steven!

Could you share the `out_files` with me so I can take a closer look?

Thanks,

Damon

**Comment by smeisler** [comment]
Sure, the files may be found here: https://drive.google.com/drive/folders/13oLnnjtnD0fpMN1InQZEygSShNFLjXyM?usp=sharing

I included a sample of 6 subject folders that contain the files I am working with. The `BayesGLM.rds` files are the result of saving the BayesGLM_cifti output (contains both hemis), and the the _left and _right files are the ones saved by the BayesGLM_cifti function itself.

Thanks,
Steven

**Comment by damondpham** [comment]
Thanks Steven! 

The first error seems to be because `BayesGLM2` isn't yet prepared to handle `rds` results with both hemispheres. I will be patching this problem soon.

The second error happens because `BayesGLM2` expects the mesh vertex counts to be the same for all subjects, but that's not true for your data. For example, there's 18472 vertices for the first subject and 18401 vertices for the second. I'll be looking into how to address this problem too.

**Comment by damondpham** [comment]
Hi Steven,

On 1.9 I added support for multi-hemisphere input. I also added the ability to support input with different meshes, but in the same resolution. (This occurs because scans in the same resolution might have different locations masked out due to low mean/variance. The different masks yield different meshes.)

Could you try downloading and using the latest version? Let me know how it goes!

**Comment by damondpham** [comment]
Hi @smeisler, I was wondering if you consider this Issue and the other one (#22) solved, so that I might close them?

Thanks!

**Comment by smeisler** [comment]
I think it's fine to close it for now, I am about to revisit this with new data and updated versions, so I doubt any problems I run into in the future would be relevant here. Thanks for asking!
